name: Shoppy
description: "Visualizzatore mobile della lista della spesa di StockHouse"
version: "1.0.1"
slug: "shoppy"
url: "https://github.com/rbraico/stockhouse-shoppy"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ports:
  "9193/tcp": 9193
environment:
  DB_PATH: "/config/stockhouse/stockhouse.db"
map:
  - config:ro
options:
  theme: "light"  # Opzionale, per divertimento
schema:
  theme: str
